// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnehwoaockudqsdqwfwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZWh3b2FvY2t1ZHFzZHF3ZndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mzg0NzgsImV4cCI6MjA2NDMxNDQ3OH0.KizGzSHdn4Z3Wy96U3nympyYwr7-MSujQXYxRMM6EDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);